### ISSUE TITLE
velog API document 문의

### ISSUE THREAD

**Issue by snoop2head** [cjaewon/velog-backup#1]
https://v2.velog.io/graphql 을 기반으로 크롤링하신 것 같은데, 어떤 API Document를 참고하셨는지 알 수 있을까요?
감사합니다.

**Comment by cjaewon** [comment]
Velog 는 Api Document 가 따로 정의되어있지는 않은 것 같아서 크롬 네트워크 탭에서 요청하는 쿼리를수정해서 만들었어요 😊

**Comment by snoop2head** [comment]
아 문서가 별도로 있는 게 아니었군요?? 
개인 gatsby 블로그 <-> velog를 sync할 수 있는 방법을 찾고 있어서 여쭤봤습니다 ㅎㅎ
graphql playground의 docs랑 schema, @cjaewon 님이 알려주신 네트워크 탭도 활용하도록 하겠습니다.
답변 감사합니다 👍

**Comment by cjaewon** [comment]
오.. 재미있는 프로젝트 진행 중이시네요
이슈 감사합니다 🙏🙏
