### ISSUE TITLE
타 서비스에서 velog-backup 써드파티 대한 언급의 건

### ISSUE THREAD

**Issue by Nuung** [cjaewon/velog-backup#15]
안녕하세요, 
저는 최근에 https://velog-dashboard.kro.kr 를 만들어서 오픈한 개발자 정현우 라고 합니다 :)

해당 레포(velog-backup)를 제가 velog과 함께 쓰기 좋은 써드파티로 링크를 걸거나 또는 소개를 하려고 합니다.
위 서비스에 velog 써드파티에 대한 정보를 취합해서 업데이트를 하려고 합니다!
velog-backup 에 대한 언급을 해도 괜찮을까 해서, `issue` 로 글을 먼저 남겨봅니다!

감사합니다. 

참고 글 - (https://velog.io/@qlgks1/velog-dashboard-%EC%A0%9C%EC%9E%91%EA%B8%B0-%EB%B2%A8%EB%A1%9C%EA%B7%B8-%ED%86%B5%EA%B3%84%EB%A5%BC-%ED%8E%B8%ED%95%98%EA%B2%8C-%EB%B3%B4%EA%B3%A0-%EC%8B%B6%EC%96%B4%EC%9A%94-%E3%85%A0)

**Comment by cjaewon** [comment]
넵, 상관없습니다!
