### ISSUE TITLE
velog 비공개 글 백업 문의

### ISSUE THREAD

**Issue by somnode** [cjaewon/velog-backup#4]
안녕하세요

해당 프로젝트로 velog 백업을 하니까 공개글만 백업이 됩니다.
비공개 글의 경우도 인증(?)을 통해 백업을 할 수 있었으면 좋겠습니다..

해당 기능 추가가 가능할지 문의드립니다.

**Comment by cjaewon** [comment]
[1.0.1 버전](https://github.com/cjaewon/velog-backup/releases/tag/1.0.1) 릴리즈로 `cert` 옵션을 사용하실 수 있습니다.
밑에 사진처럼 velog access_token 을 넣어주시면 비공개글 또한 백업 할 수 있습니다.

```
node app.js -u <username> -c <access_token>
```

이슈 감사합니다!
