### ISSUE TITLE
파일명 excludedChar 관련

### ISSUE THREAD

**Issue by ino5** [cjaewon/velog-backup#5]
안녕하세요. 포스트 제목에 같은 종류의 excludedChar 문자가 2번 이상 들어간 경우 오류가 발생합니다.
예를들어 포스트 제목이 `테스트 <> 123>` 과 같은 경우에 폴더를 생성하지 못해 아래와 같은 오류가 발생합니다.

![화면 캡처 2021-04-28 124905](https://user-images.githubusercontent.com/70236767/116343806-24844480-a820-11eb-98a3-0b7334b7b69e.png)

<br><br>

https://github.com/cjaewon/velog-backup/blob/1c1c01b9be82c5d9ed0b2e1f883a515ec86c1ae9/crawler/index.js#L96-L98

index.js L96-L98에 대해서 여러 개의 같은 종류의 excludedChar 문자도 제거할 수 있도록 수정하면 해결될 것 같습니다. 

<br><br>

임시방편으로 아래와 같이 코드를 수정하니 해당 문제가 사라졌습니다.

```javascript
    for (const char of excludedChar) {
      let count = 0;
      let indexOfChar = title.indexOf(char);
      while (indexOfChar !== -1) {
          count++;
          indexOfChar = title.indexOf(char, indexOfChar + 1);

      }
      for (let i = 0; i < count; i++) {
          title = title.replace(char, '');
      }
  }
```

감사합니다.

**Comment by cjaewon** [comment]
오류 제보 감사합니다! 
해당 오류는 `replace` 함수가 특수문자 한개만 치환해서 발생하는 문제로 해결하여 [1.0.2 버전](https://github.com/cjaewon/velog-backup/releases/tag/1.0.2) 으로 배포하였습니다.
https://github.com/cjaewon/velog-backup/blob/9201ecde981fc199ec515dd774371a749469fd7d/crawler/index.js#L92-L99
