### ISSUE TITLE
velog 게시글 작성 시, 자동으로 비공개 전환

### ISSUE THREAD

**Issue by minssseo** [cjaewon/velog-backup#6]
velog에 게시글 작성 시, 전체 공개로 출간하였는데,
자동으로 비공개 전환이 되어 외부에서 접근 불가능한 게시글이 있습니다.

혹시 글 내부적으로 문제가 있어서 자동으로 비공개로 출간이 되는건가요?

**Comment by cjaewon** [comment]
velog 관련 문제는 velopert 님한테 문의하셔야 할 것 같아요.
https://github.com/velopert/velog-client/
