### ISSUE TITLE
readme 설명 보충

### ISSUE THREAD

**Issue by minpeter** [cjaewon/velog-backup#9]
![image](https://user-images.githubusercontent.com/62207008/156955450-2a820441-0d2d-447d-89b8-c0d0d1c0fd76.png)
큰 문제가 아니고 readme 문서 "👋 사용법"에서 클론, 디렉토리 변경 후 `yarn install` 또는 `npm install`을 수행하지 않아 오류가 발생합니다.

**Comment by cjaewon** [comment]
수정했습니다 🙇‍♂️
